"""Seeded synthetic document generator, PDF rendering and FUNSD conversion.

Everything here is deterministic given a seed so the evaluation set can be
regenerated byte-for-byte and versioned by hash in ``data/MANIFEST.txt``.
"""
